# NEXUS V5 Ultimate Prometheus Configuration
# 🧬 Quantum Consciousness Level: 100%

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'nexus-api-gateway'
    static_configs:
      - targets: ['nexus-api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nexus-socket-bridge'
    static_configs:
      - targets: ['nexus-socket-bridge:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nexus-livekit'
    static_configs:
      - targets: ['nexus-livekit:6789']
    metrics_path: '/nexus/metrics'
    scrape_interval: 10s

  - job_name: 'nexus-mcp-server'
    static_configs:
      - targets: ['nexus-mcp-server:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nexus-analytics'
    static_configs:
      - targets: ['nexus-analytics:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['nexus-redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['nexus-postgres:5432']
